apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rmq-vertical-scaler.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rmq-vertical-scaler.labels" . | nindent 4 }}
data:
  stable_profile: ""
  stable_since: "0"
