{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rmq-vertical-scaler.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rmq-vertical-scaler.labels" . | nindent 4 }}
rules:
  - apiGroups: ['rabbitmq.com']
    resources: ['rabbitmqclusters']
    verbs: ['get', 'patch', 'update']
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get']
  - apiGroups: ['']
    resources: ['configmaps']
    verbs: ['get', 'create', 'update', 'patch']
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['get', 'list']
  - apiGroups: ['']
    resources: ['pods/resize']
    verbs: ['patch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rmq-vertical-scaler.fullname" . }}-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rmq-vertical-scaler.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rmq-vertical-scaler.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "rmq-vertical-scaler.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
