{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rmq-vertical-scaler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rmq-vertical-scaler.labels" . | nindent 4 }}
{{- end }}
